<a href="https://colab.research.google.com/github/cashby-890/ST-554-HW6/blob/main/ST554_Homework_Six_Part_One_Cody_Ashby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ST 554 Homework Six Part I by Cody Ashby**

## ***More SQL Practice***

In [ ]:
import sqlite3
con = sqlite3.connect("lahman_1871-2022.sqlite")

In [ ]:
cursor = con.cursor()
get_schema='''
        select *
        from sqlite_schema
        where type="table";
        '''
cursor.execute(get_schema)
result=cursor.fetchall()
cursor.close()

In [ ]:
import pandas as pd
lahman_df=pd.read_sql(get_schema,con)
lahman_df

,type,name,tbl_name,rootpage,sql
0,table,AllstarFull,AllstarFull,2,"CREATE TABLE AllstarFull (\nplayerID TEXT,\nye..."
1,table,Appearances,Appearances,3,"CREATE TABLE Appearances (\nyearID INTEGER,\nt..."
2,table,AwardsManagers,AwardsManagers,4,"CREATE TABLE AwardsManagers (\nplayerID TEXT,\..."
3,table,AwardsPlayers,AwardsPlayers,5,"CREATE TABLE AwardsPlayers (\nplayerID TEXT,\n..."
4,table,AwardsShareManagers,AwardsShareManagers,6,CREATE TABLE AwardsShareManagers (\nawardID TE...
5,table,AwardsSharePlayers,AwardsSharePlayers,7,CREATE TABLE AwardsSharePlayers (\nawardID TEX...
6,table,Batting,Batting,8,"CREATE TABLE Batting (\nplayerID TEXT,\nyearID..."
7,table,BattingPost,BattingPost,9,"CREATE TABLE BattingPost (\nyearID INTEGER,\nr..."
8,table,CollegePlaying,CollegePlaying,10,"CREATE TABLE CollegePlaying (\nplayerID TEXT,\..."
9,table,Fielding,Fielding,11,"CREATE TABLE Fielding (\nplayerID TEXT,\nyearI..."
10,table,FieldingOF,FieldingOF,12,"CREATE TABLE FieldingOF (\nplayerID TEXT,\nyea..."
11,table,FieldingOFsplit,FieldingOFsplit,13,"CREATE TABLE FieldingOFsplit (\nplayerID TEXT,..."
12,table,FieldingPost,FieldingPost,14,"CREATE TABLE FieldingPost (\nplayerID TEXT,\ny..."
13,table,HallOfFame,HallOfFame,15,"CREATE TABLE HallOfFame (\nplayerID TEXT,\nyea..."
14,table,HomeGames,HomeGames,16,"CREATE TABLE HomeGames (\nyearkey INTEGER,\nle..."
15,table,Managers,Managers,17,"CREATE TABLE Managers (\nplayerID TEXT,\nyearI..."
16,table,ManagersHalf,ManagersHalf,18,"CREATE TABLE ManagersHalf (\nplayerID TEXT,\ny..."
17,table,Parks,Parks,19,"CREATE TABLE Parks (\nID INTEGER,\nparkalias T..."
18,table,People,People,21,"CREATE TABLE People (\nID INTEGER,\nplayerID T..."
19,table,Pitching,Pitching,23,"CREATE TABLE Pitching (\nplayerID TEXT,\nyearI..."
20,table,PitchingPost,PitchingPost,24,"CREATE TABLE PitchingPost (\nplayerID TEXT,\ny..."
21,table,Salaries,Salaries,25,"CREATE TABLE Salaries (\nyearID INTEGER,\nteam..."
22,table,Schools,Schools,26,"CREATE TABLE Schools (\nschoolID TEXT,\nname_f..."
23,table,SeriesPost,SeriesPost,27,"CREATE TABLE SeriesPost (\nyearID INTEGER,\nro..."
24,table,Teams,Teams,28,"CREATE TABLE Teams (\nyearID INTEGER,\nlgID TE..."
25,table,TeamsFranchises,TeamsFranchises,29,"CREATE TABLE TeamsFranchises (\nfranchID TEXT,..."
26,table,TeamsHalf,TeamsHalf,30,"CREATE TABLE TeamsHalf (\nyearID INTEGER,\nlgI..."

In [ ]:
pd.read_sql("select * from Pitching",con)

,playerID,yearID,stint,teamID,lgID,W,L,G,GS,CG,...,IBB,WP,HBP,BK,BFP,GF,R,SH,SF,GIDP
0,aardsda01,2004,1,SFN,NL,1,0,11,0,0,...,0.0,0,2.0,0,61.0,5,8,0.0,1.0,1.0
1,aardsda01,2006,1,CHN,NL,3,0,45,0,0,...,0.0,1,1.0,0,225.0,9,25,1.0,3.0,2.0
2,aardsda01,2007,1,CHA,AL,2,1,25,0,0,...,3.0,2,1.0,0,151.0,7,24,2.0,1.0,1.0
3,aardsda01,2008,1,BOS,AL,4,2,47,0,0,...,2.0,3,5.0,0,228.0,7,32,3.0,2.0,4.0
4,aardsda01,2009,1,SEA,AL,3,6,73,0,0,...,3.0,2,0.0,0,296.0,53,23,2.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50397,zuverge01,1958,1,BAL,AL,2,2,45,0,0,...,3.0,2,6.0,0,294.0,23,29,NaN,NaN,NaN
50398,zuverge01,1959,1,BAL,AL,0,1,6,0,0,...,0.0,1,0.0,0,55.0,1,7,NaN,NaN,NaN
50399,zychto01,2015,1,SEA,AL,0,0,13,1,0,...,0.0,1,2.0,0,76.0,4,6,0.0,0.0,0.0
50400,zychto01,2016,1,SEA,AL,1,0,12,0,0,...,2.0,0,1.0,0,60.0,3,6,0.0,1.0,1.0
50401,zychto01,2017,1,SEA,AL,6,3,45,0,0,...,3.0,1,5.0,1,173.0,7,12,1.0,2.0,5.0

In [ ]:
pd.read_sql("select * from Batting",con)

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old
0,aardsda01,2004,1,SFN,NL,11,None,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,None
1,aardsda01,2006,1,CHN,NL,45,None,2,0,0,...,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,None
2,aardsda01,2007,1,CHA,AL,25,None,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,None
3,aardsda01,2008,1,BOS,AL,47,None,1,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,None
4,aardsda01,2009,1,SEA,AL,73,None,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112179,zwilldu01,1915,1,CHF,FL,150,None,548,65,157,...,24.0,NaN,67,65.0,NaN,2.0,18.0,NaN,NaN,None
112180,zwilldu01,1916,1,CHN,NL,35,None,53,4,6,...,0.0,NaN,4,6.0,NaN,0.0,2.0,NaN,NaN,None
112181,zychto01,2015,1,SEA,AL,13,None,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,None
112182,zychto01,2016,1,SEA,AL,12,None,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,None
112183,zychto01,2017,1,SEA,AL,45,None,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,None

In [ ]:
pd.read_sql("select * from HallOfFame where inducted='Y'",con)

,playerID,yearid,votedBy,ballots,needed,votes,inducted,category,needed_note
0,aaronha01,1982,BBWAA,415.0,312.0,406.0,Y,Player,None
1,alexape01,1938,BBWAA,262.0,197.0,212.0,Y,Player,None
2,alomaro01,2011,BBWAA,581.0,436.0,523.0,Y,Player,None
3,alstowa01,1983,Veterans,NaN,NaN,NaN,Y,Manager,None
4,andersp01,2000,Veterans,NaN,NaN,NaN,Y,Manager,None
...,...,...,...,...,...,...,...,...,...
335,yastrca01,1989,BBWAA,447.0,336.0,423.0,Y,Player,None
336,yawketo99,1980,Veterans,NaN,NaN,NaN,Y,Pioneer/Executive,None
337,youngcy01,1937,BBWAA,201.0,151.0,153.0,Y,Player,None
338,youngro01,1972,Veterans,NaN,NaN,NaN,Y,Player,None
339,yountro01,1999,BBWAA,497.0,373.0,385.0,Y,Player,None

In [ ]:
inner_1="""
    select distinct P.playerID,sum(P.GS),sum(P.G),sum(P.W),sum(P.L),sum(IPOuts),sum(CG),sum(SHO),sum(SV) from Pitching as P
    inner join HallOfFame as H on H.playerID=P.playerID
    where H.inducted='Y'
    group by P.playerID
    """
HOF_Pitching_Stats=pd.read_sql(inner_1,con)
HOF_Pitching_Stats

,playerID,sum(P.GS),sum(P.G),sum(P.W),sum(P.L),sum(IPOuts),sum(CG),sum(SHO),sum(SV)
0,alexape01,599,696,373,208,15570,437,90,32
1,ansonca01,0,3,0,1,12,0,0,1
2,becklja01,1,1,0,1,12,0,0,0
3,bendech01,334,459,212,127,9051,255,40,34
4,blylebe01,685,692,287,250,14910,242,60,0
...,...,...,...,...,...,...,...,...,...
103,willivi01,471,513,249,205,11988,388,50,11
104,wrighge01,0,3,0,1,15,0,0,0
105,wrighha01,8,36,4,4,301,0,0,14
106,wynnea01,612,691,300,244,13692,290,49,15
107,youngcy01,815,906,511,315,22068,749,76,18

In [ ]:
inner_2="""
    select distinct B.playerID,sum(AB),sum(R),sum(H),sum(HR),sum(RBI),sum(BB),sum(SO) from Batting as B
    inner join HallOfFame as H on H.playerID=B.playerID
    where H.inducted='Y'
    group by B.playerID
    """
HOF_Batting_Stats=pd.read_sql(inner_2,con)
HOF_Batting_Stats

      playerID  sum(AB)  sum(R)  sum(H)  sum(HR)  sum(RBI)  sum(BB)  sum(SO)
0    aaronha01    12364    2174    3771      755      2297     1402     1383
1    alexape01     1810     154     378       11       163       77      276
2    alomaro01     9073    1508    2724      210      1134     1032     1140
3    alstowa01        1       0       0        0         0        0        1
4    andersp01      477      42     104        0        34       42       53
..         ...      ...     ...     ...      ...       ...      ...      ...
266   wynnea01     1704     136     365       17       173      141      330
267  yastrca01    11988    1816    3419      452      1844     1845     1393
268  youngcy01     2960     325     623       18       290       81      381
269  youngro01     4627     812    1491       42       592      550      390
270  yountro01    11008    1632    3142      251      1406      966     1350

[271 rows x 8 columns]